network:
  ethernets:
    ens33:
      addresses:
      - 10.11.12.123/24
      nameservers:
        addresses:
        - 10.11.12.1
        - 10.11.12.2
        search:
        - domain.com
      routes:
      - to: default
        via: 10.11.12.254
  version: 2
